---
- name: prepare probe
  shell: "gluster peer probe {{ item }}"
  with_items: "{{ groups.gluster_server }}"
  

- name: Configure Gluster volume.
  gluster_volume:
    state: present
    name: "{{ gluster_brick_name }}"
    brick: "{{ gluster_brick_dir }}"
    replicas: "{{ groups['gluster_server'] | length }}"
    cluster: "{{ groups.gluster_server | join(',') }}"
    force: yes
  run_once: true  

- name: start gluster volume
  gluster_volume: state=started name={{ gluster_brick_name }}